### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by nxfxcom** [drawrowfly/amazon-keyword-suggestion-golang#1]
Hello,

when running I get the following error:

G:\DATA\amazon-keywords>akst -keyword "iphone" -limit 300
Collect 300 relevant keywords to the keyword 'iphone'
Keywords (0/300)   --- [--------------------------------------------------------------------]   0%
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x68 pc=0x4d8269]

goroutine 7 [running]:
compress/gzip.(*Reader).Close(0x0, 0x0, 0x0)
        /usr/local/go/src/compress/gzip/gunzip.go:292 +0x29
panic(0x6c8920, 0x953a30)
        /usr/local/go/src/runtime/panic.go:679 +0x1c0
compress/gzip.(*Reader).Read(0x0, 0xc000234000, 0x200, 0x200, 0xc0000f7d38, 0x40c1e0, 0xc0001226e0)
        /usr/local/go/src/compress/gzip/gunzip.go:247 +0x3e
encoding/json.(*Decoder).refill(0xc0001226e0, 0xc0001226e0, 0x40909c)
        /usr/local/go/src/encoding/json/stream.go:161 +0xf2
encoding/json.(*Decoder).readValue(0xc0001226e0, 0x0, 0x0, 0x708f40)
        /usr/local/go/src/encoding/json/stream.go:136 +0x1e3
encoding/json.(*Decoder).Decode(0xc0001226e0, 0x6a5240, 0xc000232000, 0x1c50c0, 0x0)
        /usr/local/go/src/encoding/json/stream.go:63 +0x80
main.requestKeyWords(0xc0000ca1e0, 0xc00000a0d0, 0x6, 0x0)
        /Users/karl.wint/Documents/projects/golang/steebie/amazon-keyword-research/bin/main.go:201 +0x11a6
created by main.main
        /Users/karl.wint/Documents/projects/golang/steebie/amazon-keyword-research/bin/main.go:89 +0x3c5

And FYI, this "/Users/karl.wint" is not me!

**Comment by drawrowfly** [comment]
This week I will take a look at the issue closely

**Comment by BurakaKrishna** [comment]
@drawrowfly 
@nxfxcom i have got the same error too

**Comment by drawrowfly** [comment]
i will push renewed version soon

**Comment by drawrowfly** [comment]
Pushed new release. Works perfect
